In [ ]:
!pip install scikit-learn
# scikit-learn 설치하기

In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
# 1차원 데이터
x = np.arange(10)
# array + range
# 0부터 10미만의 숫자를 배열로 반환

print(x, type(x))
print(x.shape)

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
(10,)


In [3]:
# 2차원 데이터
x = np.arange(10).reshape(-1, 1)
# 기존 데이터는 유지하고 차원과 형상을 바꾸는데 사용
# 배열의 안의 값은 유지하고 차원을 변경
# -1로 설정하면 나머지를 자동으로 맞춤

print(x, type(x))
print(x.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]] <class 'numpy.ndarray'>
(10, 1)


In [4]:
x1 = np.arange(10).reshape(2, -1)
# -1로 설정하면 나머지를 자동으로 맞춤

x2 = np.arange(10).reshape(5, -1)

print(x1)
print(x2)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [5]:
#y = (2*x + 1)
y = (2*x + 1).reshape(-1, 1)

In [6]:
print(y)
print(y.shape)

[[ 1]
 [ 3]
 [ 5]
 [ 7]
 [ 9]
 [11]
 [13]
 [15]
 [17]
 [19]]
(10, 1)


## 모델의 선언, fit(학습), predict(예측)

In [7]:
# 모델 선언, 인스턴스(객체) 생성

model = LinearRegression()
# 선형 회귀 (Linear Regression)
# 회귀 : 연속적인 타깃을 예측하는 알고리즘

In [8]:
model

LinearRegression()

In [9]:
# 학습
model.fit(x, y)
# x : 문제
# y : 결과
# (X_train, Y_train)

LinearRegression()

In [10]:
print(x)
print(y)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[ 1]
 [ 3]
 [ 5]
 [ 7]
 [ 9]
 [11]
 [13]
 [15]
 [17]
 [19]]


In [11]:
# 예측
prediction = model.predict([[10.0]])

In [12]:
prediction

array([[21.]])

In [13]:
prediction = model.predict([[215.0]])

In [14]:
prediction

array([[431.]])