## 1. Numpy import 하기

In [1]:
import numpy

In [2]:
numpy

<module 'numpy' from 'c:\\users\\bsy37\\jupyter\\lib\\site-packages\\numpy\\__init__.py'>

### 1-1. 별칭 (alias) 지정하기 (항상 np로 지정하기!!)

In [3]:
import numpy as np

In [4]:
np

<module 'numpy' from 'c:\\users\\bsy37\\jupyter\\lib\\site-packages\\numpy\\__init__.py'>

## 2. ndarray 생성하기

In [5]:
arr = np.array([1, 2, 3, 4], dtype=int)

In [6]:
arr

array([1, 2, 3, 4])

In [7]:
list = [1, 2, 3, 4]
type(list)

list

In [8]:
type(arr)

numpy.ndarray

### 2-1. list로 부터 생성하기

In [9]:
mylist1 = [1, 2, 3, 4]

In [10]:
mylist2 = [[1, 2, 3, 4], 
           [5, 6, 7, 8]]

In [11]:
arr1 = np.array(mylist1)
print(arr1, type(arr1))

[1 2 3 4] <class 'numpy.ndarray'>


In [12]:
arr2 = np.array(mylist2)
print(arr2, type(arr2))

[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'>


### 2-2. shape확인하기 : 행렬의 차원

In [13]:
arr1.shape

(4,)

In [14]:
arr2.shape

(2, 4)

## 3. array에서의 data 타입

array에서는 list와는 다르게 1개의 **단일 데이터 타입**만 허용 됩니다.

### 3-1. list에서의 data 타입

In [15]:
mylist = [1, 3.14, 'hello', '1234']

In [16]:
mylist

[1, 3.14, 'hello', '1234']

In [17]:
mylist[1]

3.14

In [18]:
mylist[2]

'hello'

### 3-2. array에서의 data 타입 (case를 통한 연구)

### case 1. int와 float 타입이 혼재된 경우

In [19]:
arr = np.array([1, 2, 3, 3.14])

In [20]:
arr

array([1.  , 2.  , 3.  , 3.14])

In [21]:
type(arr[0])

numpy.float64

### case 2. int와 float 타입이 혼재되었으나, dtype을 지정한 경우

In [22]:
arr = np.array([1, 2, 3, 3.14], dtype=int)

In [23]:
arr

array([1, 2, 3, 3])

In [24]:
type(arr[0])

numpy.int32

### case 3. int와 str 타입이 혼재된 경우

In [25]:
arr = np.array([1, 3.14, '테디', '1234'])

In [26]:
arr

array(['1', '3.14', '테디', '1234'], dtype='<U32')

In [27]:
type(arr[0])

numpy.str_

In [28]:
arr[0] + arr[1]

'13.14'

### case 4. int와 str 타입이 혼재되어 있고 int로 dtype을 지정한 경우

In [29]:
arr = np.array([1, 3.14, '1234'], dtype=int)

In [30]:
arr

array([   1,    3, 1234])

In [31]:
type(arr[0])

numpy.int32