In [1]:
import numpy as np

## 1. 슬라이싱 (Slicing)

배열의 부분 선택 (과일을 슬라이스해서 부분만 먹듯..)

In [2]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr.shape

(10,)

### 1-1. index 지정하여 색인

#### 1차원 array

In [4]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr[0]

0

In [6]:
arr[5]

5

In [7]:
arr[10]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [8]:
arr[-1]

9

In [9]:
arr[-10]

0

In [10]:
arr[-11]

IndexError: index -11 is out of bounds for axis 0 with size 10

#### 2차원 array

In [11]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

In [12]:
arr2d.shape

(3, 4)

arr2d[행, 열]

In [13]:
arr2d[0, 2]

3

In [14]:
arr2d[2, 1]

10

### 1-2. 범위 색인

#### 1차원

index 1**이상** 끝까지

In [15]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

index 5 **미만** 까지

In [17]:
arr[:5]

array([0, 1, 2, 3, 4])

index 1이상 5미만

In [18]:
arr[1:5]

array([1, 2, 3, 4])

In [19]:
arr[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

#### 2차원

In [20]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

row(행)을 모두 가져오려는 경우

In [21]:
arr2d[0, :]

array([1, 2, 3, 4])

column(열)을 모두 가져오려는 경우

In [22]:
arr2d[:, 2]

array([ 3,  7, 11])

부분 적으로 가져오려는 경우

In [23]:
arr2d[:2, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
arr2d[:2, 2:]

array([[3, 4],
       [7, 8]])

## 2. Fancy 인덱싱

fancy 인덱싱은 범위가 아닌 **특정 index의 집합의 값을 선택하여 추출**하고 싶을 때 활용합니다.

In [25]:
arr = np.array([10, 23, 2, 7, 90, 65, 32, 66, 70])

반드시 **[추출하고 싶은 인덱스]** 꺾쇠 괄호로 묶어 주세요

In [26]:
idx = [1, 3, 5]

In [27]:
arr[idx]

array([23,  7, 65])

변수에 지정 후 추출도 가능합니다.

In [28]:
idx = [1, 3, 5]

In [29]:
arr[idx]

array([23,  7, 65])

### 2-2. 2차원 array

In [30]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

In [31]:
arr2d[[0, 1], :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [32]:
arr2d[:, [1, 2, 3]]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

## 3. Boolean 인덱싱

조건 필터링을 통하여 Boolean 값을 이용한 색인 (말이 어렵다..)

In [33]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

In [34]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

### 3-1. True와 False 값으로 색인하기

In [35]:
myTrueFalse = [True, False, True]

In [36]:
arr[myTrueFalse]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 7 but corresponding boolean dimension is 3

In [37]:
myTrueFalse = [True, False, True, False, True, False, True]

In [38]:
arr[myTrueFalse]

array([1, 3, 5, 7])

### 3-2. 조건필터

조건 연산자를 활용하여 필터를 생성할 수 있습니다

In [39]:
arr2d > 2

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

필터를 활용하여 필터에 True 조건만 색인 합니다.

이럴 때 꺾쇠 괄호로 한 번 더 묶어만 주면 됩니다. (꺾쇠 괄호 안에 조건문 삽입) 

arr2d[**조건필터**]

In [40]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

In [41]:
arr2d[ arr2d > 2 ]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [42]:
arr2d[ arr2d < 5 ]

array([1, 2, 3, 4])