In [1]:
import numpy as np

## 1. 1차원 정렬

1차원 정렬은 매우 간단합니다.

In [2]:
arr = np.array([1, 10, 5, 8, 2, 4, 3, 6, 8, 7, 9])

In [3]:
arr

array([ 1, 10,  5,  8,  2,  4,  3,  6,  8,  7,  9])

np.sort(arr)

In [4]:
np.sort(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

기본적으로 오름차순 정렬을 수행합니다.

In [5]:
np.sort(arr)[::-1]

array([10,  9,  8,  8,  7,  6,  5,  4,  3,  2,  1])

내림차순 정렬은 옵션에 -1 값을 주면됩니다.

하지만, 이 값들은 **유지가 되지 않습니다**!

값을 sort 된 상태로 저장하려면, 배열 자체에 sort를 해줄 수 있습니다.

In [6]:
np.sort(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [7]:
arr2 = np.sort(arr)

In [8]:
arr

array([ 1, 10,  5,  8,  2,  4,  3,  6,  8,  7,  9])

In [9]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [10]:
arr.sort()

In [11]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

## 2. N차원 정렬

In [12]:
arr2d = np.array([[5, 6, 7, 8], 
                  [4, 3, 2, 1],
                  [10, 9, 12, 11]])

In [13]:
arr2d.shape

(3, 4)

In [14]:
arr2d

array([[ 5,  6,  7,  8],
       [ 4,  3,  2,  1],
       [10,  9, 12, 11]])

### 2-1. 열 정렬 (왼쪽에서 오른쪽으로)

In [15]:
arr2d

array([[ 5,  6,  7,  8],
       [ 4,  3,  2,  1],
       [10,  9, 12, 11]])

In [16]:
np.sort(arr2d, axis=1)

array([[ 5,  6,  7,  8],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

### 2-2. 행 정렬 (위에서 아래로)

In [17]:
arr2d

array([[ 5,  6,  7,  8],
       [ 4,  3,  2,  1],
       [10,  9, 12, 11]])

In [18]:
np.sort(arr2d, axis=0)

array([[ 4,  3,  2,  1],
       [ 5,  6,  7,  8],
       [10,  9, 12, 11]])

## 3. index를 반환하는 argsort

정렬된 값을 반환하는 것이 아닌 index를 반환합니다.

In [19]:
arr2d = np.array([[5, 6, 7, 8], 
                  [4, 3, 2, 1],
                  [10, 9, 12, 11]])


### 3-1. 열 정렬 (왼쪽에서 오른쪽으로)

In [20]:
np.argsort(arr2d, axis=1)

array([[0, 1, 2, 3],
       [3, 2, 1, 0],
       [1, 0, 3, 2]])

### 3-2. 행 정렬

In [21]:
arr2d

array([[ 5,  6,  7,  8],
       [ 4,  3,  2,  1],
       [10,  9, 12, 11]])

In [22]:
np.sort(arr2d, axis=0)

array([[ 4,  3,  2,  1],
       [ 5,  6,  7,  8],
       [10,  9, 12, 11]])

In [23]:
np.argsort(arr2d, axis=0)

array([[1, 1, 1, 1],
       [0, 0, 0, 0],
       [2, 2, 2, 2]])